// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ServicosApp.Infrastructure.Data;

#nullable disable

namespace ServicosApp.Infrastructure.PostgresMigrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507193800_AddUpdatedAtToContas")]
    partial class AddUpdatedAtToContas
    {
    }
}
